import os
import glob

def compile_prompts():
    prompt_dir = 'system_prompt'
    output_file = 'GEMINI.md'

    files = sorted(glob.glob(os.path.join(prompt_dir, '*.md')))

    with open(output_file, 'w', encoding='utf-8') as outfile:
        # Add Warning Header
        outfile.write("<!--\n")
        outfile.write("⚠️ WARNING: This file is auto-generated!\n")
        outfile.write("Do NOT edit this file directly.\n")
        outfile.write(f"Edit the source files in `{prompt_dir}/` and run `python3 compile_prompts.py`.\n")
        outfile.write("-->\n\n")

        for filepath in files:
            filename = os.path.basename(filepath)

            # Add Source Marker
            outfile.write(f"<!-- Source: {filename} -->\n")

            with open(filepath, 'r', encoding='utf-8') as infile:
                outfile.write(infile.read())

            # Add separation
            outfile.write("\n\n")

    print(f"Successfully compiled {len(files)} files into {output_file}")

if __name__ == "__main__":
    compile_prompts()
