import os
import glob
import sys

def compile_prompts():
    prompt_dir = "system_prompt"
    output_file = "GEMINI.md"

    if not os.path.exists(prompt_dir):
        print(f"Error: Directory '{prompt_dir}' not found.")
        sys.exit(1)

    files = sorted(glob.glob(os.path.join(prompt_dir, "*.md")))
    if not files:
        print(f"No markdown files found in {prompt_dir}")
        sys.exit(1)

    print(f"Compiling {len(files)} files into {output_file}...")

    compiled_content = []

    # Add Header
    header = """<!--
DO NOT EDIT THIS FILE DIRECTLY.
This file is auto-generated from the individual files in the 'system_prompt/' directory.
To make changes, edit the source files and run 'python3 compile_prompts.py'.
-->

"""
    compiled_content.append(header)

    for filepath in files:
        filename = os.path.basename(filepath)
        marker = f"<!-- Source: {filename} -->\n"

        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        compiled_content.append(marker)
        compiled_content.append(content)
        # Add a newline separator if needed
        if not content.endswith("\n"):
            compiled_content.append("\n")
        compiled_content.append("\n")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("".join(compiled_content))

    print("Compilation successful.")

if __name__ == "__main__":
    compile_prompts()
