import os
import sys

def compile_prompts():
    system_prompt_dir = 'system_prompt'
    output_file = 'GEMINI.md'

    if not os.path.exists(system_prompt_dir):
        print(f"Directory {system_prompt_dir} not found.")
        sys.exit(1)

    print(f"Compiling prompts from {system_prompt_dir} to {output_file}...")

    compiled_content = []

    # Add auto-generation warning
    compiled_content.append("<!--")
    compiled_content.append("WARNING: This file is auto-generated from the files in system_prompt/.")
    compiled_content.append("Do not edit this file directly. Edit the source files instead.")
    compiled_content.append("-->\n")

    files = sorted([f for f in os.listdir(system_prompt_dir) if f.endswith('.md')])

    for filename in files:
        filepath = os.path.join(system_prompt_dir, filename)
        print(f"Processing {filename}...")

        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        compiled_content.append(f"<!-- Source: {filename} -->")
        compiled_content.append(content)
        compiled_content.append("\n") # Ensure separation

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(compiled_content))

    print(f"Successfully created {output_file}")

if __name__ == "__main__":
    compile_prompts()
